name: Run Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_call:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
