version: '3.8'

services:
  app:
    image: python:3.11-slim
    restart: "always"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/app

    working_dir: /app
    command: sh -c "pip install -r requirements.txt
      && python run_app.py"
