name: Pylint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11",]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Install Ruff
      #   run: pip install ruff
      # - name: Run Ruff
      #   run: ruff check .
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.4.15"
          enable-cache: true
      - name: Run Ruff
        run: uvx ruff check